"""Deterministically generate ROS 2 files from a canonical vehicle export."""

from __future__ import annotations

import hashlib
import json
import math
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

import yaml

from .model import effective_sensor_pose, fastlivo_extrinsics, footprint


GENERATED_NOTICE = "Generated by agribot_vehicle_config_tools. Do not edit by hand."


def _number(value: float) -> str:
    if abs(value) < 5e-13:
        return "0"
    return f"{value:.12g}"


def _sequence(values: list[float]) -> str:
    return " ".join(_number(value) for value in values)


def _pose_text(pose: dict[str, Any]) -> str:
    return f"{_sequence(pose['xyz'])} {_sequence(pose['rpy'])}"


def _yaml_dump(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        f"# {GENERATED_NOTICE}\n"
        + yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def _sensor_map(config: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {sensor["id"]: sensor for sensor in config["sensors"]}


def _wheel_map(config: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {wheel["id"]: wheel for wheel in config["geometry"]["wheelCenters"]}


def generate_sensor_mounts(config: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {
        "vehicle_id": config["vehicleId"],
        "base_link_reference": config["baseFrame"]["reference"],
    }
    for sensor in config["sensors"]:
        pose = effective_sensor_pose(sensor)
        item = {
            "parent_frame": config["baseFrame"]["frameId"],
            "child_frame": sensor.get("measurementFrameId") or sensor["frameId"],
            "xyz": pose["xyz"],
            "rpy": pose["rpy"],
            "model": sensor["model"],
        }
        if sensor.get("role"):
            item["role"] = sensor["role"]
        result[sensor["id"]] = item
    return result


def generate_nav2_geometry(config: dict[str, Any]) -> dict[str, Any]:
    points = footprint(config)
    geometry = config["geometry"]
    navigation = config["navigation"]
    return {
        "/**": {
            "ros__parameters": {
                "vehicle_id": config["vehicleId"],
                "base_frame": config["baseFrame"]["frameId"],
                "footprint": points,
                "footprint_string": json.dumps(points, separators=(",", ":")),
                "inflation_radius": navigation["inflationRadiusM"],
                "cost_scaling_factor": navigation["costScalingFactor"],
                "motion_model": "Ackermann" if config["vehicleType"] == "ackermann" else "DiffDrive",
                "minimum_turning_radius": geometry["minTurningRadiusM"],
                "allow_reverse": navigation["allowReverse"],
                "max_linear_velocity": navigation["maxLinearSpeedMps"],
                "max_angular_velocity": navigation["maxAngularSpeedRadps"],
            }
        }
    }


def generate_kinematics(config: dict[str, Any]) -> dict[str, Any]:
    geometry = config["geometry"]
    navigation = config["navigation"]
    dynamics = config.get("dynamics", {})
    chassis = config["chassis"]
    return {
        "/**": {
            "ros__parameters": {
                "wheelbase_m": geometry["wheelbaseM"],
                "front_track_m": geometry["frontTrackM"],
                "rear_track_m": geometry["rearTrackM"],
                "wheel_radius_m": geometry["wheelRadiusM"],
                "wheel_width_m": geometry["wheelWidthM"],
                "max_steering_angle_rad": geometry["maxSteeringAngleRad"],
                "min_turning_radius_m": geometry["minTurningRadiusM"],
                "navigation_max_linear_velocity": navigation["maxLinearSpeedMps"],
                "navigation_max_angular_velocity": navigation["maxAngularSpeedRadps"],
                "max_linear_velocity": chassis["commandMaxLinearSpeedMps"],
                "max_angular_velocity": chassis["commandMaxAngularSpeedRadps"],
                "minimum_motion_speed": chassis["minimumMotionSpeedMps"],
                "max_acceleration_mps2": dynamics.get("maxAccelerationMps2", 0.8),
                "max_steering_rate_radps": dynamics.get("maxSteeringRateRadps", 1.2),
            }
        }
    }


def generate_fastlivo_config(config: dict[str, Any]) -> dict[str, Any]:
    extrinsics = fastlivo_extrinsics(config)
    return {
        "/**": {
            "ros__parameters": {
                "extrin_calib": extrinsics,
            }
        }
    }


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"ROS configuration template does not exist: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _patch_nav2(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    geometry = config["geometry"]
    navigation = config["navigation"]
    dynamics = config.get("dynamics", {})
    footprint_text = json.dumps(footprint(config), separators=(",", ":"))

    controller_server = template.get("controller_server")
    if controller_server is not None:
        follow_path = controller_server["ros__parameters"]["FollowPath"]
        follow_path["vx_max"] = navigation["maxLinearSpeedMps"]
        follow_path["vx_min"] = (
            -navigation["maxLinearSpeedMps"] if navigation["allowReverse"] else 0.0
        )
        follow_path["wz_max"] = navigation["maxAngularSpeedRadps"]
        follow_path["ax_max"] = dynamics.get(
            "maxAccelerationMps2", follow_path.get("ax_max", 0.8)
        )
        follow_path["ax_min"] = -follow_path["ax_max"]
        follow_path["motion_model"] = "Ackermann"
        follow_path.setdefault("AckermannConstraints", {})[
            "min_turning_r"
        ] = geometry["minTurningRadiusM"]
        if "PathAngleCritic" in follow_path:
            follow_path["PathAngleCritic"]["forward_preference"] = not navigation[
                "allowReverse"
            ]
        if "PreferForwardCritic" in follow_path:
            follow_path["PreferForwardCritic"]["enabled"] = not navigation[
                "allowReverse"
            ]

    for costmap_name in ("global_costmap", "local_costmap"):
        if costmap_name not in template:
            continue
        parameters = template[costmap_name][costmap_name]["ros__parameters"]
        parameters["footprint"] = footprint_text
        inflation = parameters.get("inflation_layer")
        if inflation is not None:
            inflation["inflation_radius"] = navigation["inflationRadiusM"]
            inflation["cost_scaling_factor"] = navigation["costScalingFactor"]

    planner_server = template.get("planner_server")
    if planner_server is not None:
        planner = planner_server["ros__parameters"]["GridBased"]
        planner["motion_model_for_search"] = (
            "REEDS_SHEPP" if navigation["allowReverse"] else "DUBIN"
        )
        planner["minimum_turning_radius"] = geometry["minTurningRadiusM"]
        if "analytic_expansion_max_length" in planner:
            planner["analytic_expansion_max_length"] = max(
                planner["analytic_expansion_max_length"],
                4.0 * geometry["minTurningRadiusM"],
            )
    return template


def _patch_simulation_nav2(
    template: dict[str, Any], config: dict[str, Any]
) -> dict[str, Any]:
    """Apply vehicle geometry and reject Gazebo returns on the lidar plane."""
    template = _patch_nav2(template, config)
    lidar_z = effective_sensor_pose(_sensor_map(config)["lidar"])["xyz"][2]
    min_obstacle_height = lidar_z + 0.02

    for costmap_name in ("global_costmap", "local_costmap"):
        costmap = template.get(costmap_name)
        if costmap is None:
            continue
        parameters = costmap[costmap_name]["ros__parameters"]
        marking = parameters.get("stvl_layer", {}).get("lidar_mark")
        if marking is not None:
            marking["min_obstacle_height"] = min_obstacle_height
    return template


def _patch_chassis(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    parameters = template["/**"]["ros__parameters"]
    geometry = config["geometry"]
    chassis = config["chassis"]
    parameters["wheelbase_m"] = geometry["wheelbaseM"]
    parameters["max_steering_angle_rad"] = geometry["maxSteeringAngleRad"]
    parameters["max_linear_velocity"] = chassis["commandMaxLinearSpeedMps"]
    parameters["max_angular_velocity"] = chassis["commandMaxAngularSpeedRadps"]
    parameters["minimum_motion_speed"] = chassis["minimumMotionSpeedMps"]
    return template


def _patch_joint_state(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    parameters = template["/**"]["ros__parameters"]
    geometry = config["geometry"]
    parameters.update(
        {
            "wheelbase_m": geometry["wheelbaseM"],
            "front_track_m": geometry["frontTrackM"],
            "rear_track_m": geometry["rearTrackM"],
            "wheel_radius_m": geometry["wheelRadiusM"],
            "max_steering_angle_rad": geometry["maxSteeringAngleRad"],
        }
    )
    return template


def _patch_fastlivo(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    template["/**"]["ros__parameters"]["extrin_calib"] = fastlivo_extrinsics(config)
    return template


def _patch_fastlio(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    extrinsics = fastlivo_extrinsics(config)
    mapping = template["/**"]["ros__parameters"]["mapping"]
    mapping["extrinsic_T"] = extrinsics["extrinsic_T"]
    mapping["extrinsic_R"] = extrinsics["extrinsic_R"]
    return template


def _patch_bridge(
    template: dict[str, Any], config: dict[str, Any], sensor_id: str
) -> dict[str, Any]:
    pose = effective_sensor_pose(_sensor_map(config)[sensor_id])
    parameters = template["fastlio_odom_bridge"]["ros__parameters"]
    parameters["base_to_body_xyz"] = pose["xyz"]
    parameters["base_to_body_rpy"] = pose["rpy"]
    return template


def _patch_initial_localizer(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    pose = effective_sensor_pose(_sensor_map(config)["lidar"])
    parameters = template["pcd_initial_localizer"]["ros__parameters"]
    parameters["base_to_body_xyz"] = pose["xyz"]
    parameters["base_to_body_rpy"] = pose["rpy"]
    return template


def _patch_rtk_initializer(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    pose = effective_sensor_pose(_sensor_map(config)["rtk_master"])
    template["rtk_map_initializer"]["ros__parameters"][
        "base_to_master_antenna_m"
    ] = pose["xyz"]
    return template


def _patch_kf_gins(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    sensors = _sensor_map(config)
    imu_pose = effective_sensor_pose(sensors["imu"])
    antenna_pose = effective_sensor_pose(sensors["rtk_master"])
    parameters = template["rtk_eskf_localization"]["ros__parameters"]
    parameters["base_to_imu_m"] = imu_pose["xyz"]
    parameters["base_to_imu_rpy_rad"] = imu_pose["rpy"]
    parameters["antlever_m"] = [
        antenna_pose["xyz"][index] - imu_pose["xyz"][index] for index in range(3)
    ]
    return template


def _patch_fusion(template: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    sensors = _sensor_map(config)
    imu_pose = effective_sensor_pose(sensors["imu"])
    antenna_pose = effective_sensor_pose(sensors["rtk_master"])
    parameters = template["fastlivo_rtk_fusion"]["ros__parameters"]
    parameters["base_to_antenna_xyz"] = antenna_pose["xyz"]
    parameters["base_from_imu_rpy"] = imu_pose["rpy"]
    return template


def _write_patched_yaml(
    source: Path,
    destination: Path,
    config: dict[str, Any],
    patcher,
) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    _yaml_dump(destination, patcher(_load_yaml(source), config))


def _set_xml_text(parent: ET.Element, query: str, value: Any) -> None:
    element = parent.find(query)
    if element is None:
        raise ValueError(f"required SDF element is missing: {query}")
    element.text = str(value)


def generate_simulation_sdf(
    config: dict[str, Any], workspace_src: Path, unity_export_dir: Path
) -> str:
    simulation = workspace_src / "agribot_ackermann_mppi"
    vehicle_tree = ET.parse(simulation / "models" / "ackermann_scout.sdf")
    sensor_tree = ET.parse(simulation / "models" / "ackermann_scout_sensor.sdf")
    model = vehicle_tree.getroot().find("model")
    sensor_model = sensor_tree.getroot().find("model")
    if model is None or sensor_model is None:
        raise ValueError("Ackermann SDF templates must contain one model")
    model.set("name", config["vehicleId"])

    geometry = config["geometry"]
    navigation = config["navigation"]
    dynamics = config.get("dynamics", {})
    collision = config.get("collision", {})
    base = model.find("./link[@name='base_link']")
    sensor_base = sensor_model.find("./link[@name='base_link']")
    if base is None or sensor_base is None:
        raise ValueError("Ackermann SDF templates must contain base_link")

    center = collision.get("center", dynamics.get("centerOfMass", [0.0, 0.0, 0.0]))
    size = collision.get("size")
    _set_xml_text(base, "./inertial/pose", f"{_sequence(dynamics.get('centerOfMass', center))} 0 0 0")
    _set_xml_text(base, "./inertial/mass", _number(dynamics.get("massKg", 50.0)))
    inertia = dynamics.get("inertia", {})
    for key in ("ixx", "ixy", "ixz", "iyy", "iyz", "izz"):
        _set_xml_text(base, f"./inertial/inertia/{key}", _number(inertia.get(key, 0.0)))
    _set_xml_text(base, "./collision/pose", f"{_sequence(center)} 0 0 0")
    if size is not None:
        _set_xml_text(base, "./collision/geometry/box/size", _sequence(size))

    unity_mesh = unity_export_dir / "vehicle_visual.obj"
    if unity_mesh.is_file():
        body_visual = base.find("./visual[@name='vehicle_body_visual']")
        if body_visual is not None:
            _set_xml_text(body_visual, "./pose", "0 0 0 0 0 0")
            _set_xml_text(
                body_visual,
                "./geometry/mesh/uri",
                config["visuals"][0]["meshUri"],
            )

    wheel_map = _wheel_map(config)
    for wheel_id, wheel in wheel_map.items():
        pose = f"{_sequence(wheel['position'])} 0 0 0"
        _set_xml_text(model, f"./link[@name='{wheel_id}_wheel_link']/pose", pose)
        _set_xml_text(model, f"./joint[@name='{wheel_id}_wheel_joint']/pose", pose)
        if wheel["steering"]:
            _set_xml_text(model, f"./link[@name='{wheel_id}_steering_link']/pose", pose)
            _set_xml_text(model, f"./joint[@name='{wheel_id}_steering_joint']/pose", pose)
            _set_xml_text(
                model,
                f"./joint[@name='{wheel_id}_steering_joint']/axis/limit/lower",
                _number(-geometry["maxSteeringAngleRad"]),
            )
            _set_xml_text(
                model,
                f"./joint[@name='{wheel_id}_steering_joint']/axis/limit/upper",
                _number(geometry["maxSteeringAngleRad"]),
            )
        wheel_link = model.find(f"./link[@name='{wheel_id}_wheel_link']")
        _set_xml_text(wheel_link, "./collision/geometry/cylinder/radius", _number(geometry["wheelRadiusM"]))
        _set_xml_text(wheel_link, "./collision/geometry/cylinder/length", _number(geometry["wheelWidthM"]))

    plugin = model.find("./plugin[@name='ackermann_drive']")
    if plugin is None:
        raise ValueError("Ackermann drive plugin is missing from SDF template")
    plugin_values = {
        "wheelbase": geometry["wheelbaseM"],
        "front_track_width": geometry["frontTrackM"],
        "rear_track_width": geometry["rearTrackM"],
        "wheel_radius": geometry["wheelRadiusM"],
        "max_steering_angle": geometry["maxSteeringAngleRad"],
        "max_steering_rate": dynamics.get("maxSteeringRateRadps", 1.2),
        "max_speed": navigation["maxLinearSpeedMps"],
        "max_accel": dynamics.get("maxAccelerationMps2", 0.8),
    }
    for key, value in plugin_values.items():
        _set_xml_text(plugin, key, _number(value))

    sensor_names = {
        "imu": "n300pro_imu",
        "lidar": "lslidar_c16_points",
        "right_camera": "hikrobot_right_camera",
    }
    sensors = _sensor_map(config)
    for sensor_id, sdf_name in sensor_names.items():
        sensor_xml = sensor_base.find(f"./sensor[@name='{sdf_name}']")
        if sensor_xml is None:
            raise ValueError(f"sensor is missing from SDF template: {sdf_name}")
        sensor = sensors[sensor_id]
        _set_xml_text(sensor_xml, "pose", _pose_text(sensor["pose"]))
        _set_xml_text(sensor_xml, "update_rate", _number(sensor.get("updateRateHz", 10.0)))
        base.append(sensor_xml)

    ET.indent(vehicle_tree, space="  ")
    return ET.tostring(vehicle_tree.getroot(), encoding="unicode") + "\n"


def generate_runtime_files(
    config: dict[str, Any], source: Path, workspace_src: Path, output: Path
) -> None:
    hardware = workspace_src / "agribot_hardware_bringup"
    simulation = workspace_src / "agribot_ackermann_mppi"
    fastlivo = workspace_src / "FAST-LIVO2"
    physical = output / "config" / "physical"
    simulated = output / "config" / "simulation"

    physical_templates = {
        "nav2_params_ackermann_fastlio_local.yaml": (
            hardware / "ackermann/config/nav2_params_ackermann_fastlio_local.yaml",
            _patch_nav2,
        ),
        "nav2_params_ackermann_fastlio_mapped.yaml": (
            hardware / "ackermann/config/nav2_params_ackermann_fastlio_mapped.yaml",
            _patch_nav2,
        ),
        "nav2_params_ackermann_navsat_static.yaml": (
            hardware / "ackermann/config/nav2_params_ackermann_navsat_static.yaml",
            _patch_nav2,
        ),
        "nav2_params_ackermann_planner_only.yaml": (
            hardware / "ackermann/config/nav2_params_ackermann_planner_only.yaml",
            _patch_nav2,
        ),
        "chassis_can.yaml": (hardware / "ackermann/config/chassis_can.yaml", _patch_chassis),
        "chassis_serial.yaml": (hardware / "ackermann/config/chassis_serial.yaml", _patch_chassis),
        "joint_state_publisher.yaml": (
            hardware / "ackermann/config/joint_state_publisher.yaml",
            _patch_joint_state,
        ),
        "fast_lio_c16.yaml": (hardware / "config/fast_lio_c16.yaml", _patch_fastlio),
        "fastlio_bridge.yaml": (
            hardware / "config/fastlio_bridge.yaml",
            lambda data, value: _patch_bridge(data, value, "imu"),
        ),
        "fastlivo_bridge.yaml": (
            hardware / "config/fastlivo_bridge.yaml",
            lambda data, value: _patch_bridge(data, value, "imu"),
        ),
        "pcd_initial_localization.yaml": (
            hardware / "ackermann/config/pcd_initial_localization.yaml",
            _patch_initial_localizer,
        ),
        "rtk_map_initializer.yaml": (
            hardware / "config/rtk_map_initializer.yaml",
            _patch_rtk_initializer,
        ),
        "kf_gins_n300pro.yaml": (
            hardware / "config/kf_gins_n300pro.yaml",
            _patch_kf_gins,
        ),
        "fastlivo_rtk_fusion.yaml": (
            hardware / "config/fastlivo_rtk_fusion.yaml",
            _patch_fusion,
        ),
        "agribot_c16_astra.yaml": (
            fastlivo / "config/agribot_c16_astra.yaml",
            _patch_fastlivo,
        ),
    }
    for name, (template, patcher) in physical_templates.items():
        _write_patched_yaml(template, physical / name, config, patcher)
    _yaml_dump(physical / "sensor_mounts.yaml", generate_sensor_mounts(config))

    for name in (
        "nav2_params_ackermann.yaml",
        "nav2_params_ackermann_fastlio_static.yaml",
        "nav2_params_ackermann_navsat_static.yaml",
    ):
        _write_patched_yaml(
            simulation / "config" / name,
            simulated / name,
            config,
            _patch_simulation_nav2,
        )

    (output / "models" / f"{config['vehicleId']}.sdf").write_text(
        generate_simulation_sdf(config, workspace_src, source.parent),
        encoding="utf-8",
    )


def _sensor_visual(sensor: dict[str, Any]) -> str:
    sensor_type = sensor["sensorType"]
    if sensor_type == "lidar":
        geometry = "<cylinder radius=\"0.04\" length=\"0.08\"/>"
    elif sensor_type == "gnss_antenna":
        geometry = "<cylinder radius=\"0.0225\" length=\"0.036\"/>"
    elif sensor_type == "camera":
        geometry = "<box size=\"0.044 0.04 0.04\"/>"
    else:
        geometry = "<box size=\"0.05 0.04 0.015\"/>"
    return f"<geometry>{geometry}</geometry>"


def generate_urdf(config: dict[str, Any]) -> str:
    geometry = config["geometry"]
    dynamics = config.get("dynamics", {})
    collision = config.get("collision", {})
    collision_center = collision.get("center", [0.0, 0.0, geometry["wheelRadiusM"]])
    collision_size = collision.get(
        "size",
        [
            geometry["bodyExtents"]["frontM"] + geometry["bodyExtents"]["rearM"],
            geometry["bodyExtents"]["leftM"] + geometry["bodyExtents"]["rightM"],
            geometry["wheelRadiusM"] * 2.0,
        ],
    )
    center_of_mass = dynamics.get("centerOfMass", collision_center)
    inertia = dynamics.get(
        "inertia",
        {"ixx": 1.0, "ixy": 0.0, "ixz": 0.0, "iyy": 1.0, "iyz": 0.0, "izz": 1.0},
    )
    body_visuals = []
    for visual in config.get("visuals", []):
        body_visuals.append(
            f"""    <visual name="{escape(visual['name'])}">
      <origin xyz="{_sequence(visual['pose']['xyz'])}" rpy="{_sequence(visual['pose']['rpy'])}"/>
      <geometry><mesh filename="{escape(visual['meshUri'])}" scale="{_sequence(visual.get('scale', [1.0, 1.0, 1.0]))}"/></geometry>
    </visual>"""
        )

    sensor_blocks = []
    for sensor in config["sensors"]:
        pose = sensor["pose"]
        sensor_blocks.append(
            f"""  <link name="{escape(sensor['frameId'])}">
    <visual>{_sensor_visual(sensor)}</visual>
  </link>
  <joint name="{escape(sensor['id'])}_mount_joint" type="fixed">
    <origin xyz="{_sequence(pose['xyz'])}" rpy="{_sequence(pose['rpy'])}"/>
    <parent link="base_link"/><child link="{escape(sensor['frameId'])}"/>
  </joint>"""
        )
        if sensor.get("measurementFrameId"):
            measurement = sensor["measurementFramePose"]
            sensor_blocks.append(
                f"""  <link name="{escape(sensor['measurementFrameId'])}"/>
  <joint name="{escape(sensor['id'])}_measurement_joint" type="fixed">
    <origin xyz="{_sequence(measurement['xyz'])}" rpy="{_sequence(measurement['rpy'])}"/>
    <parent link="{escape(sensor['frameId'])}"/><child link="{escape(sensor['measurementFrameId'])}"/>
  </joint>"""
            )

    wheel_blocks = []
    for wheel in config["geometry"]["wheelCenters"]:
        wheel_id = wheel["id"]
        parent = "base_link"
        if wheel["steering"]:
            steering_link = f"{wheel_id}_steering_link"
            wheel_blocks.append(
                f"""  <link name="{steering_link}"/>
  <joint name="{wheel_id}_steering_joint" type="revolute">
    <origin xyz="{_sequence(wheel['position'])}" rpy="0 0 0"/>
    <parent link="base_link"/><child link="{steering_link}"/>
    <axis xyz="0 0 1"/>
    <limit lower="-{_number(geometry['maxSteeringAngleRad'])}" upper="{_number(geometry['maxSteeringAngleRad'])}" effort="200" velocity="1.5"/>
  </joint>"""
            )
            parent = steering_link
            origin = [0.0, 0.0, 0.0]
        else:
            origin = wheel["position"]
        wheel_blocks.append(
            f"""  <link name="{wheel_id}_wheel_link">
    <visual><origin rpy="1.570796326795 0 0"/><geometry><cylinder radius="{_number(geometry['wheelRadiusM'])}" length="{_number(geometry['wheelWidthM'])}"/></geometry></visual>
    <collision><origin rpy="1.570796326795 0 0"/><geometry><cylinder radius="{_number(geometry['wheelRadiusM'])}" length="{_number(geometry['wheelWidthM'])}"/></geometry></collision>
  </link>
  <joint name="{wheel_id}_wheel_joint" type="continuous">
    <origin xyz="{_sequence(origin)}" rpy="0 0 0"/>
    <parent link="{parent}"/><child link="{wheel_id}_wheel_link"/>
    <axis xyz="0 1 0"/>
  </joint>"""
        )

    return f"""<?xml version="1.0"?>
<!-- {GENERATED_NOTICE} -->
<robot name="{escape(config['vehicleId'])}" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="base_link">
    <inertial>
      <origin xyz="{_sequence(center_of_mass)}" rpy="0 0 0"/>
      <mass value="{_number(dynamics.get('massKg', 50.0))}"/>
      <inertia ixx="{_number(inertia['ixx'])}" ixy="{_number(inertia['ixy'])}" ixz="{_number(inertia['ixz'])}" iyy="{_number(inertia['iyy'])}" iyz="{_number(inertia['iyz'])}" izz="{_number(inertia['izz'])}"/>
    </inertial>
    <collision><origin xyz="{_sequence(collision_center)}" rpy="0 0 0"/><geometry><box size="{_sequence(collision_size)}"/></geometry></collision>
{chr(10).join(body_visuals)}
  </link>
{chr(10).join(sensor_blocks)}
{chr(10).join(wheel_blocks)}
</robot>
"""


def generate_sdf(config: dict[str, Any]) -> str:
    geometry = config["geometry"]
    navigation = config["navigation"]
    dynamics = config.get("dynamics", {})
    collision = config.get("collision", {})
    center = collision.get("center", [0.0, 0.0, geometry["wheelRadiusM"]])
    size = collision.get(
        "size",
        [
            geometry["bodyExtents"]["frontM"] + geometry["bodyExtents"]["rearM"],
            geometry["bodyExtents"]["leftM"] + geometry["bodyExtents"]["rightM"],
            geometry["wheelRadiusM"] * 2.0,
        ],
    )
    inertia = dynamics.get(
        "inertia",
        {"ixx": 1.0, "ixy": 0.0, "ixz": 0.0, "iyy": 1.0, "iyz": 0.0, "izz": 1.0},
    )
    visuals = []
    for visual in config.get("visuals", []):
        visuals.append(
            f"""      <visual name="{escape(visual['name'])}"><pose>{_pose_text(visual['pose'])}</pose><geometry><mesh><uri>{escape(visual['meshUri'])}</uri><scale>{_sequence(visual.get('scale', [1.0, 1.0, 1.0]))}</scale></mesh></geometry></visual>"""
        )

    sensors = _sensor_map(config)
    imu = sensors["imu"]
    lidar = sensors["lidar"]
    camera = sensors["right_camera"]
    sensor_xml = f"""
      <sensor name="configured_imu" type="imu"><pose>{_pose_text(imu['pose'])}</pose><always_on>true</always_on><update_rate>{_number(imu.get('updateRateHz', 100.0))}</update_rate><plugin name="imu_controller" filename="libgazebo_ros_imu_sensor.so"><ros><remapping>~/out:={escape(imu.get('topic', '/imu/data'))}</remapping></ros><frame_name>{escape(imu['frameId'])}</frame_name></plugin></sensor>
      <sensor name="configured_c16" type="ray"><pose>{_pose_text(lidar['pose'])}</pose><always_on>true</always_on><update_rate>{_number(lidar.get('updateRateHz', 10.0))}</update_rate><ray><scan><horizontal><samples>2000</samples><resolution>1</resolution><min_angle>-3.14159265359</min_angle><max_angle>3.14159265359</max_angle></horizontal><vertical><samples>16</samples><resolution>1</resolution><min_angle>-0.279252680319</min_angle><max_angle>0.244346095279</max_angle></vertical></scan><range><min>0.3</min><max>100</max><resolution>0.01</resolution></range></ray><plugin name="c16_controller" filename="libgazebo_ros_velodyne_laser.so"><ros><remapping>~/out:={escape(lidar.get('topic', '/lidar/points'))}</remapping></ros><frame_name>{escape(lidar['frameId'])}</frame_name><organize_cloud>false</organize_cloud></plugin></sensor>
      <sensor name="configured_camera" type="camera"><pose>{_pose_text(camera['pose'])}</pose><always_on>true</always_on><update_rate>{_number(camera.get('updateRateHz', 10.0))}</update_rate><camera><horizontal_fov>0.936241091175</horizontal_fov><image><width>1280</width><height>1024</height><format>R8G8B8</format></image><clip><near>0.05</near><far>100</far></clip></camera><plugin name="camera_controller" filename="libgazebo_ros_camera.so"><ros><remapping>camera/image_raw:={escape(camera.get('topic', '/camera/rgb/image_raw'))}</remapping></ros><camera_name>camera</camera_name><frame_name>{escape(camera.get('measurementFrameId', camera['frameId']))}</frame_name></plugin></sensor>"""

    wheel_links = []
    wheel_joints = []
    for wheel in geometry["wheelCenters"]:
        wheel_id = wheel["id"]
        wheel_links.append(
            f"""    <link name="{wheel_id}_wheel_link"><pose relative_to="__model__">{_sequence(wheel['position'])} 0 0 0</pose><inertial><mass>3</mass><inertia><ixx>0.01223</ixx><iyy>0.02438</iyy><izz>0.01223</izz></inertia></inertial><collision name="collision"><pose>0 0 0 1.570796326795 0 0</pose><geometry><cylinder><radius>{_number(geometry['wheelRadiusM'])}</radius><length>{_number(geometry['wheelWidthM'])}</length></cylinder></geometry></collision><visual name="visual"><pose>0 0 0 1.570796326795 0 0</pose><geometry><cylinder><radius>{_number(geometry['wheelRadiusM'])}</radius><length>{_number(geometry['wheelWidthM'])}</length></cylinder></geometry></visual></link>"""
        )
        if wheel["steering"]:
            steering_id = f"{wheel_id}_steering_link"
            wheel_links.append(
                f"    <link name=\"{steering_id}\"><pose relative_to=\"__model__\">{_sequence(wheel['position'])} 0 0 0</pose><inertial><mass>0.2</mass><inertia><ixx>0.0001</ixx><iyy>0.0001</iyy><izz>0.0001</izz></inertia></inertial></link>"
            )
            wheel_joints.append(
                f"    <joint name=\"{wheel_id}_steering_joint\" type=\"revolute\"><pose relative_to=\"__model__\">{_sequence(wheel['position'])} 0 0 0</pose><parent>base_link</parent><child>{steering_id}</child><axis><xyz>0 0 1</xyz><limit><lower>-{_number(geometry['maxSteeringAngleRad'])}</lower><upper>{_number(geometry['maxSteeringAngleRad'])}</upper><effort>200</effort><velocity>1.5</velocity></limit></axis></joint>"
            )
            parent = steering_id
        else:
            parent = "base_link"
        wheel_joints.append(
            f"    <joint name=\"{wheel_id}_wheel_joint\" type=\"revolute\"><pose relative_to=\"__model__\">{_sequence(wheel['position'])} 0 0 0</pose><parent>{parent}</parent><child>{wheel_id}_wheel_link</child><axis><xyz>0 1 0</xyz><limit><lower>-1e16</lower><upper>1e16</upper><effort>200</effort><velocity>100</velocity></limit></axis></joint>"
        )

    return f"""<sdf version="1.7">
  <!-- {GENERATED_NOTICE} -->
  <model name="{escape(config['vehicleId'])}">
    <allow_auto_disable>false</allow_auto_disable>
    <link name="base_link">
      <inertial><pose>{_sequence(dynamics.get('centerOfMass', center))} 0 0 0</pose><mass>{_number(dynamics.get('massKg', 50.0))}</mass><inertia><ixx>{_number(inertia['ixx'])}</ixx><ixy>{_number(inertia['ixy'])}</ixy><ixz>{_number(inertia['ixz'])}</ixz><iyy>{_number(inertia['iyy'])}</iyy><iyz>{_number(inertia['iyz'])}</iyz><izz>{_number(inertia['izz'])}</izz></inertia></inertial>
      <collision name="body_collision"><pose>{_sequence(center)} 0 0 0</pose><geometry><box><size>{_sequence(size)}</size></box></geometry></collision>
{chr(10).join(visuals)}
{sensor_xml}
    </link>
{chr(10).join(wheel_links)}
{chr(10).join(wheel_joints)}
    <plugin name="ackermann_drive" filename="libagribot_ackermann_mppi_drive.so"><ros><namespace>/</namespace></ros><cmd_vel_topic>/nav2/cmd_vel</cmd_vel_topic><odom_topic>/odom</odom_topic><joint_state_topic>/joint_states</joint_state_topic><odom_frame>odom</odom_frame><base_frame>base_link</base_frame><wheelbase>{_number(geometry['wheelbaseM'])}</wheelbase><front_track_width>{_number(geometry['frontTrackM'])}</front_track_width><rear_track_width>{_number(geometry['rearTrackM'])}</rear_track_width><wheel_radius>{_number(geometry['wheelRadiusM'])}</wheel_radius><max_steering_angle>{_number(geometry['maxSteeringAngleRad'])}</max_steering_angle><max_steering_rate>{_number(dynamics.get('maxSteeringRateRadps', 1.2))}</max_steering_rate><max_speed>{_number(navigation['maxLinearSpeedMps'])}</max_speed><max_accel>{_number(dynamics.get('maxAccelerationMps2', 0.8))}</max_accel><command_timeout>0.5</command_timeout><publish_rate>30</publish_rate><publish_tf>false</publish_tf></plugin>
  </model>
</sdf>
"""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate_bundle(
    config: dict[str, Any],
    source: Path,
    output: Path,
    workspace_src: Path | None = None,
) -> dict[str, Any]:
    config_dir = output / "config"
    urdf_dir = output / "urdf"
    models_dir = output / "models"
    for directory in (config_dir, urdf_dir, models_dir):
        directory.mkdir(parents=True, exist_ok=True)

    canonical_copy = output / "vehicle_config.json"
    canonical_copy.write_text(
        json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    _yaml_dump(config_dir / "sensor_mounts.yaml", generate_sensor_mounts(config))
    _yaml_dump(config_dir / "nav2_geometry.yaml", generate_nav2_geometry(config))
    _yaml_dump(config_dir / "ackermann_kinematics.yaml", generate_kinematics(config))
    _yaml_dump(config_dir / "fastlivo_extrinsics.yaml", generate_fastlivo_config(config))
    (urdf_dir / f"{config['vehicleId']}.urdf.xacro").write_text(
        generate_urdf(config), encoding="utf-8"
    )
    (models_dir / f"{config['vehicleId']}.sdf").write_text(
        generate_sdf(config), encoding="utf-8"
    )

    unity_export_dir = source.parent
    for asset_name in ("vehicle_visual.obj", "vehicle_visual.mtl"):
        asset = unity_export_dir / asset_name
        if asset.is_file():
            shutil.copy2(asset, models_dir / asset.name)

    if workspace_src is not None:
        generate_runtime_files(config, source, workspace_src, output)

    generated_files = sorted(
        path for path in output.rglob("*") if path.is_file() and path.name != "manifest.json"
    )
    manifest = {
        "schemaVersion": "1.0",
        "vehicleId": config["vehicleId"],
        "sourceFile": source.name,
        "generator": "agribot_vehicle_config_tools 0.1.0",
        "coordinateConvention": "ROS_FLU",
        "runtimeTemplatesApplied": workspace_src is not None,
        "files": [
            {
                "path": str(path.relative_to(output)),
                "sizeBytes": path.stat().st_size,
                "sha256": _sha256(path),
            }
            for path in generated_files
        ],
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest
