fastlio_map_anchor:
  ros__parameters:
    odom_topic: /fastlio/odometry
    pose_topic: /localization_pose
    initial_pose_topic: /initialpose
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    initial_pose: [0.0, 0.0, 0.0]
    allow_reinitialization: true
    stamp_with_current_time: false
