kiss_icp_node:
  ros__parameters:
    data:
      deskew: false
      max_range: 25.0
      min_range: 0.3

    mapping:
      max_points_per_voxel: 20

    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.1
