mobile_gateway:
  ros__parameters:
    http_host: 0.0.0.0
    http_port: 8088
    api_token: ""
    map_root: /home/sunrise/agribot_maps/test_site
    bag_root: /mnt/agribot_data/bags
    required_collection_mount: /mnt/agribot_data
    process_log_root: /home/sunrise/agribot_mobile_logs
    semantic_service_url: http://172.18.80.26:8090
    semantic_map_ids: [map_lio_sam_0811, map_lio_sam_zoulang_0813_indoor]
    processing_enabled: false
    processing_domain_id: 71
    processing_playback_rate: 0.5
    pose_topic: /fastlivo_rtk/odometry
    trajectory_topic: /fastlivo_rtk/path
    global_plan_topic: /plan
    local_plan_topic: /transformed_global_plan
    footprint_topic: /local_costmap/published_footprint
    vehicle_footprint: [0.754818, 0.485974, 0.754818, -0.485974, -0.227500, -0.485974, -0.227500, 0.485974]
    map_topic: /map
    global_costmap_topic: /global_costmap/costmap
    local_costmap_topic: /local_costmap/costmap
    semantic_filter_info_topic: /semantic_navigation/costmap_filter_info
    semantic_filter_mask_topic: /semantic_navigation/costmap_mask
